# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/esp_common/test_apps/esp_common:
  disable:
    - if: CONFIG_NAME == "psram" and SOC_SPIRAM_SUPPORTED != 1
    - if: CONFIG_NAME == "psram_noinit" and SOC_SPIRAM_SUPPORTED != 1
    - if: CONFIG_NAME == "psram_noinit" and IDF_TARGET in ["esp32c61"]
      temporary: true
      reason: esp32c61 is not supported yet # TODO: IDF-9293
