# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/esp_timer/test_apps:
  disable:
    - if: IDF_TARGET in ["esp32c6"]
      temporary: true
      reason: Not supported yet
