# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/esp_adc/test_apps/adc:
  disable:
    - if: IDF_TARGET == "esp32c6"
      temporary: true
      reason: target esp32c6 is not supported yet
