components/esp_hal_regi2c/test_apps:
  enable:
    - if: INCLUDE_DEFAULT == 1
  disable:
    - if: IDF_TARGET in ["esp32s31"]
      temporary: true
      reason: not support yet # TODO: [ESP32S31] IDF-14680
  depends_components:
    - esp_hal_regi2c
