# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/wpa_supplicant/test_apps:
  disable:
    - if: SOC_WIFI_SUPPORTED != 1
  disable_test:
    - if: IDF_TARGET in ["esp32c5"]
      reason: leak of runner
  depends_components:
    - esp_wifi
    - wpa_supplicant
    - mbedtls
    - esp_timer
    - esp_event
