# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/newlib/test_apps/newlib:
  disable:
    - if: IDF_TARGET == "esp32c5"
      temporary: true
      reason: not supported yet  # TODO: [ESP32C5] IDF-8675
