# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/esp_adc/test_apps/adc:
  disable:
    - if: SOC_ADC_SUPPORTED != 1
    - if: CONFIG_NAME == "gdma_iram_safe" and IDF_TARGET in ["esp32", "esp32s2", "esp32c2"]
  depends_components:
    - esp_adc
    - efuse
  depends_filepatterns:
    - components/driver/gpio/**/*
    - components/driver/spi/**/* # ADC continuous driver relies on SPI on ESP32S2
    - components/driver/i2s/**/* # ADC continuous driver relies on I2S on ESP32
