# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/efuse/test_apps:
  disable_test:
    - if: IDF_TARGET in ["esp32s2", "esp32s3"]
      temporary: true
      reason: eFuse for S2 and S3 is similar to the C3 chip, so we only test for C3.
  disable:
    - if: IDF_TARGET == "esp32p4"
      temporary: true
      reason: target esp32p4 is not supported yet # TODO: IDF-7512
