# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/esp_rom/test_apps:
  disable_test:
    - if: IDF_TARGET in ["esp32", "esp32c2"]
      temporary: false
      reason: lack of memory for testing miniz compressing
  disable:
    - if: IDF_TARGET in ["esp32p4"]
      temporary: true
      reason: Not supported on p4 # TODO: IDF-8071
