# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/esp_system/test_apps/esp_system_unity_tests:
  disable:
    - if: CONFIG_NAME == "psram" and SOC_SPIRAM_SUPPORTED != 1
    - if: IDF_TARGET == "esp32p4"
      temporary: true
      reason: target esp32p4 is not supported yet

components/esp_system/test_apps/linux_apis:
  enable:
    - if: IDF_TARGET == "linux"
