# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/esp_system/test_apps/console:
  disable:
    - if: CONFIG_NAME == "serial_jtag_only" and SOC_USB_SERIAL_JTAG_SUPPORTED != 1

components/esp_system/test_apps/esp_system_unity_tests:
  disable:
    - if: IDF_TARGET == "esp32c5" or (CONFIG_NAME == "psram" and SOC_SPIRAM_SUPPORTED != 1)
      temporary: true
      reason: C5 not support yet # TODO: [ESP32C5] IDF-8690

components/esp_system/test_apps/linux_apis:
  enable:
    - if: IDF_TARGET == "linux"
