# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/spi_flash/test_apps/esp_flash:
  disable:
    - if: IDF_TARGET == "esp32p4"
      temporary: true
      reason: target esp32p4 is not supported yet # TODO: IDF-7499

components/spi_flash/test_apps/flash_encryption:
  disable_test:
    - if: IDF_TARGET in ["esp32c2", "esp32s2", "esp32c6", "esp32h2"]
      temporary: true
      reason: No runners # IDF-5634
  disable:
    - if: IDF_TARGET == "esp32p4"
      temporary: true
      reason: target esp32p4 is not supported yet # TODO: IDF-7545

components/spi_flash/test_apps/flash_suspend:
  disable:
    - if: SOC_SPI_MEM_SUPPORT_AUTO_SUSPEND != 1
    - if: IDF_TARGET == "esp32p4"
      temporary: true
      reason: target esp32p4 is not supported yet # TODO: IDF-7499
  disable_test:
    - if: IDF_TARGET != "esp32c3"
      temporary: true
      reason: lack of runners

components/spi_flash/test_apps/mspi_test:
  disable:
    - if: CONFIG_NAME == "psram" and SOC_SPIRAM_SUPPORTED != 1
    - if: CONFIG_NAME == "xip_psram" and SOC_SPIRAM_SUPPORTED != 1
    - if: CONFIG_NAME == "psram" and IDF_TARGET in ["esp32p4"]
      temporary: true
      reason: not supported yet #TODO: IDF-7499 for p4
    - if: CONFIG_NAME == "xip_psram" and IDF_TARGET in ["esp32p4"]
      temporary: true
      reason: not supported yet #TODO: IDF-7556 for p4
