# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/ieee802154/test_apps/test_ieee802154:
  enable:
    - if: IDF_TARGET == "esp32h2"
      reason: only test on esp32h2
